import '../models/recipe.dart';

// ─── Sample Recipe Data ───────────────────────────────────────────────────────
List<Recipe> getSampleRecipes() {
  return [
    Recipe(
      id: '1',
      title: 'Chicken Tikka',
      category: 'Dinner',
      cookTimeMinutes: 45,
      difficulty: 'Medium',
      imageUrl: 'https://images.unsplash.com/photo-1599487488170-d11ec9c172f0?w=600',
      rating: 4.5,
      isFavorite: true,
      ingredients: [
        Ingredient(name: 'Chicken breast', quantity: '500g'),
        Ingredient(name: 'Yogurt', quantity: '1 cup'),
        Ingredient(name: 'Tikka masala paste', quantity: '3 tbsp'),
        Ingredient(name: 'Lemon juice', quantity: '2 tbsp'),
        Ingredient(name: 'Garlic paste', quantity: '1 tbsp'),
        Ingredient(name: 'Ginger paste', quantity: '1 tbsp'),
        Ingredient(name: 'Oil', quantity: '2 tbsp'),
        Ingredient(name: 'Salt', quantity: 'to taste'),
      ],
      steps: [
        'Mix yogurt, tikka masala paste, lemon juice, garlic, ginger, and salt in a bowl.',
        'Cut chicken into cubes and marinate in the mixture for at least 2 hours.',
        'Thread chicken onto skewers.',
        'Grill or bake at 220°C for 20–25 minutes, turning halfway.',
        'Serve hot with naan and mint chutney.',
      ],
    ),
    Recipe(
      id: '2',
      title: 'Veggie Omelette',
      category: 'Breakfast',
      cookTimeMinutes: 12,
      difficulty: 'Easy',
      imageUrl: 'https://images.unsplash.com/photo-1510693206972-df098062cb71?w=600',
      rating: 4.0,
      isFavorite: false,
      ingredients: [
        Ingredient(name: 'Eggs', quantity: '3'),
        Ingredient(name: 'Bell pepper', quantity: '½'),
        Ingredient(name: 'Onion', quantity: '1 small'),
        Ingredient(name: 'Tomato', quantity: '1'),
        Ingredient(name: 'Butter', quantity: '1 tbsp'),
        Ingredient(name: 'Salt & pepper', quantity: 'to taste'),
      ],
      steps: [
        'Beat eggs with salt and pepper.',
        'Chop vegetables finely.',
        'Heat butter in a non-stick pan over medium heat.',
        'Pour in eggs and cook until edges set.',
        'Add vegetables to one half and fold over.',
        'Cook for 2 more minutes and serve.',
      ],
    ),
    Recipe(
      id: '3',
      title: 'Pasta Carbonara',
      category: 'Lunch',
      cookTimeMinutes: 25,
      difficulty: 'Medium',
      imageUrl: 'https://images.unsplash.com/photo-1621996346565-e3dbc646d9a9?w=600',
      rating: 4.8,
      isFavorite: false,
      ingredients: [
        Ingredient(name: 'Spaghetti', quantity: '200g'),
        Ingredient(name: 'Pancetta', quantity: '100g'),
        Ingredient(name: 'Egg yolks', quantity: '3'),
        Ingredient(name: 'Parmesan cheese', quantity: '50g'),
        Ingredient(name: 'Black pepper', quantity: '1 tsp'),
        Ingredient(name: 'Salt', quantity: 'to taste'),
      ],
      steps: [
        'Cook spaghetti in salted boiling water until al dente.',
        'Fry pancetta until crispy.',
        'Mix egg yolks, parmesan, and pepper in a bowl.',
        'Reserve pasta water before draining.',
        'Combine pasta with pancetta off heat, then add egg mixture.',
        'Add pasta water to loosen, stir quickly. Serve immediately.',
      ],
    ),
    Recipe(
      id: '4',
      title: 'Chocolate Lava Cake',
      category: 'Dessert',
      cookTimeMinutes: 20,
      difficulty: 'Hard',
      imageUrl: 'https://images.unsplash.com/photo-1606313564200-e75d5e30476c?w=600',
      rating: 5.0,
      isFavorite: true,
      ingredients: [
        Ingredient(name: 'Dark chocolate', quantity: '150g'),
        Ingredient(name: 'Butter', quantity: '100g'),
        Ingredient(name: 'Eggs', quantity: '2'),
        Ingredient(name: 'Egg yolks', quantity: '2'),
        Ingredient(name: 'Sugar', quantity: '60g'),
        Ingredient(name: 'Flour', quantity: '50g'),
      ],
      steps: [
        'Preheat oven to 200°C. Grease 4 ramekins.',
        'Melt chocolate and butter together.',
        'Whisk eggs, yolks, and sugar until pale.',
        'Fold chocolate into egg mixture.',
        'Fold in flour until just combined.',
        'Pour into ramekins and bake 12 minutes.',
        'Rest 1 minute then invert onto plates. Serve immediately.',
      ],
    ),
    Recipe(
      id: '5',
      title: 'Avocado Toast',
      category: 'Breakfast',
      cookTimeMinutes: 10,
      difficulty: 'Easy',
      imageUrl: 'https://images.unsplash.com/photo-1588137378633-dea1336ce1e2?w=600',
      rating: 4.2,
      isFavorite: false,
      ingredients: [
        Ingredient(name: 'Sourdough bread', quantity: '2 slices'),
        Ingredient(name: 'Ripe avocado', quantity: '1'),
        Ingredient(name: 'Lemon juice', quantity: '1 tbsp'),
        Ingredient(name: 'Red pepper flakes', quantity: 'pinch'),
        Ingredient(name: 'Salt & pepper', quantity: 'to taste'),
        Ingredient(name: 'Poached egg (optional)', quantity: '1'),
      ],
      steps: [
        'Toast bread until golden and crispy.',
        'Mash avocado with lemon juice, salt, and pepper.',
        'Spread avocado mixture on toast.',
        'Top with red pepper flakes.',
        'Add poached egg if desired and serve immediately.',
      ],
    ),
    Recipe(
      id: '6',
      title: 'Caesar Salad',
      category: 'Lunch',
      cookTimeMinutes: 15,
      difficulty: 'Easy',
      imageUrl: 'https://images.unsplash.com/photo-1546793665-c74683f339c1?w=600',
      rating: 4.3,
      isFavorite: false,
      ingredients: [
        Ingredient(name: 'Romaine lettuce', quantity: '1 head'),
        Ingredient(name: 'Caesar dressing', quantity: '4 tbsp'),
        Ingredient(name: 'Parmesan', quantity: '30g'),
        Ingredient(name: 'Croutons', quantity: '1 cup'),
        Ingredient(name: 'Black pepper', quantity: 'to taste'),
      ],
      steps: [
        'Wash and dry romaine lettuce, tear into pieces.',
        'Toss with Caesar dressing.',
        'Add croutons and shaved parmesan.',
        'Season with black pepper and serve.',
      ],
    ),
    Recipe(
      id: '7',
      title: 'Mango Smoothie',
      category: 'Snack',
      cookTimeMinutes: 5,
      difficulty: 'Easy',
      imageUrl: 'https://images.unsplash.com/photo-1623065422902-30a2d299bbe4?w=600',
      rating: 4.6,
      isFavorite: false,
      ingredients: [
        Ingredient(name: 'Mango', quantity: '1 large'),
        Ingredient(name: 'Milk', quantity: '1 cup'),
        Ingredient(name: 'Honey', quantity: '1 tbsp'),
        Ingredient(name: 'Ice cubes', quantity: '6'),
        Ingredient(name: 'Cardamom', quantity: 'pinch'),
      ],
      steps: [
        'Peel and cube the mango.',
        'Add all ingredients to a blender.',
        'Blend until smooth and creamy.',
        'Pour into glasses and serve immediately.',
      ],
    ),
    Recipe(
      id: '8',
      title: 'Beef Tacos',
      category: 'Dinner',
      cookTimeMinutes: 30,
      difficulty: 'Easy',
      imageUrl: 'https://images.unsplash.com/photo-1551504734-5ee1c4a1479b?w=600',
      rating: 4.7,
      isFavorite: false,
      ingredients: [
        Ingredient(name: 'Ground beef', quantity: '400g'),
        Ingredient(name: 'Taco shells', quantity: '8'),
        Ingredient(name: 'Taco seasoning', quantity: '1 packet'),
        Ingredient(name: 'Shredded cheese', quantity: '100g'),
        Ingredient(name: 'Lettuce', quantity: '1 cup'),
        Ingredient(name: 'Tomato', quantity: '2'),
        Ingredient(name: 'Sour cream', quantity: '½ cup'),
      ],
      steps: [
        'Brown ground beef in a skillet over medium-high heat.',
        'Add taco seasoning and ¼ cup water, simmer 5 minutes.',
        'Warm taco shells per package instructions.',
        'Fill shells with beef, then top with cheese, lettuce, tomato.',
        'Add sour cream and serve.',
      ],
    ),
  ];
}
